services:
  backend:
    build: ./backend
    ports:
      - "4567:4567"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - ./backend/db/sql/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./backend/db/sql/02_load_data.sql:/docker-entrypoint-initdb.d/02_load_data.sql
      - db-data:/var/lib/mysql
      - ./backend/db/csv:/var/lib/mysql-files
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./backend/db/sql:/sql

volumes:
  db-data:
