' 表記ルール
' 頭には主キーを記載し -- で区切る
' <<FK>> 外部キー
' <<U>> ユニークキー
' カラム名 : 型 : 説明 を書く
' * 表示修飾子は必須属性を表します。 空白を1文字後ろに入れることで、強調{**}と解釈されることを防ぐと良いでしょう:


@startuml Tmatter
hide circle
hide empty members
skinparam linetype ortho

entity memos {
    memo_id : int : メモID
    --
    title_name : char(200) : メモ名
    <<U>> posted_at : timestamp : 投稿日時
    category_id : int : 紐づけるID
    <<U>> last_updated_at : timestamp : 修正日時
    <<U>> resolved_at : timestamp : 解決日時
    user_id : int : ユーザーID
}

entity users {
    user_id : int : ユーザーID
    --
    user_name : char(100) : ユーザー名
}

entity memo_categorie {
    id : int : memo_categorieテーブルid
    --
    <<FK>> memo_id : int : メモID
    <<FK>> category_id : int : 紐づけるID
}

entity categories {
    category_id : int : 紐づけるID
    category_name : char(100) : ruby等の技術カテゴリ名
}

memo_categorie }|--|| memos
memo_categorie }|--|| categories
memos }|--|| users
@endumls